### ISSUE TITLE
Clippy and machete

### ISSUE THREAD

**Issue by martinfrances107** [Jurshsmith/rusty_group_chat#4]
Just seen your "request for comments" on slack

Can I suggest downloading and installing two useful commands "clippy" and "machete".

Both are generating suggestions that I think will help improve your project.

```bash
rustup component add clippy
cargo clippy
```

```
rustup component add machete
cargo machete
```

**Comment by Jurshsmith** [comment]
All done ✅. Thanks again for the feedback! @martinfrances107
